(function(){
  "use strict";
  var root=document.documentElement,body=document.body;
  var sidebar=document.getElementById("demo-sidebar"),overlay=document.getElementById("sidebar-overlay"),mobileMenu=document.getElementById("mobile-menu");
  var topTitle=document.getElementById("top-title"),languageButton=document.getElementById("language-button"),themeButton=document.getElementById("theme-button");
  var dialog=document.getElementById("command-dialog"),commandOpen=document.getElementById("command-open"),commandClose=document.getElementById("command-close"),commandInput=document.getElementById("command-input"),commandResults=document.getElementById("command-results"),toastStack=document.getElementById("toast-stack");
  var navButtons=Array.from(document.querySelectorAll(".demo-nav [data-view]"));var demoOrderCount=0;
  function isEnglish(){return body.classList.contains("en")}
  function activeButton(){return document.querySelector(".demo-nav [data-view].active")||navButtons[0]}
  function syncTitle(){var b=activeButton();topTitle.textContent=isEnglish()?b.dataset.titleEn:b.dataset.titleAr}
  function closeSidebar(){sidebar.classList.remove("open");overlay.classList.remove("open")}
  function setLanguage(language){var en=language==="en";body.classList.toggle("en",en);root.lang=en?"en":"ar";root.dir=en?"ltr":"rtl";syncTitle();renderCommands(commandInput.value);try{localStorage.setItem("cp-language",en?"en":"ar")}catch(_error){}}
  function setTheme(theme){root.dataset.theme=theme;themeButton.textContent=theme==="dark"?"◒":"◐";try{localStorage.setItem("cp-demo-theme",theme)}catch(_error){}}
  function showView(view){navButtons.forEach(function(b){b.classList.toggle("active",b.dataset.view===view)});document.querySelectorAll("[data-view-panel]").forEach(function(p){p.hidden=p.dataset.viewPanel!==view});syncTitle();closeSidebar();try{window.scrollTo({top:0,behavior:window.matchMedia("(prefers-reduced-motion: reduce)").matches?"auto":"smooth"})}catch(_error){}}
  function showToast(ar,en){var toast=document.createElement("div");toast.className="toast";toast.textContent=isEnglish()?en:ar;toastStack.appendChild(toast);setTimeout(function(){toast.remove()},3300)}
  function renderCommands(query){var q=(query||"").trim().toLowerCase();commandResults.replaceChildren();navButtons.filter(function(b){return !q||(b.dataset.titleAr+" "+b.dataset.titleEn).toLowerCase().includes(q)}).forEach(function(b){var item=document.createElement("button");item.type="button";var icon=document.createElement("span");icon.textContent=b.querySelector(".nav-icon").textContent;var label=document.createElement("b");label.textContent=isEnglish()?b.dataset.titleEn:b.dataset.titleAr;item.append(icon,label);item.addEventListener("click",function(){showView(b.dataset.view);dialog.close()});commandResults.appendChild(item)})}
  function updateKdsCounts(){document.querySelectorAll("[data-kds-column]").forEach(function(column){column.querySelector("[data-kds-count]").textContent=String(column.querySelectorAll("[data-ticket]").length)})}
  function advanceTicket(button){var ticket=button.closest("[data-ticket]"),column=ticket.closest("[data-kds-column]"),stage=column.dataset.kdsColumn;if(stage==="new"){document.querySelector('[data-kds-column="preparing"]').appendChild(ticket);button.querySelector("[data-ar]").textContent="جاهز للتسليم";button.querySelector("[data-en]").textContent="Mark ready";showToast("انتقل الطلب إلى قيد التجهيز","Ticket moved to preparation")}else if(stage==="preparing"){document.querySelector('[data-kds-column="ready"]').appendChild(ticket);button.querySelector("[data-ar]").textContent="تم التسليم";button.querySelector("[data-en]").textContent="Served";showToast("الطلب جاهز للتسليم","Ticket marked ready")}else{ticket.remove();showToast("أغلق الطلب داخل العرض فقط","Ticket closed inside the demo only")}updateKdsCounts()}
  navButtons.forEach(function(b){b.addEventListener("click",function(){showView(b.dataset.view)})});document.querySelectorAll("[data-view-jump]").forEach(function(b){b.addEventListener("click",function(){showView(b.dataset.viewJump)})});document.querySelectorAll("[data-toast-ar]").forEach(function(b){b.addEventListener("click",function(){showToast(b.dataset.toastAr,b.dataset.toastEn)})});
  document.querySelectorAll("[data-table-search]").forEach(function(input){input.addEventListener("input",function(){var table=document.getElementById(input.dataset.tableSearch),q=input.value.trim().toLowerCase();table.querySelectorAll("tbody tr").forEach(function(row){row.hidden=q&&!row.textContent.toLowerCase().includes(q)})})});
  document.querySelectorAll("[data-ticket-next],[data-ticket-done]").forEach(function(button){button.addEventListener("click",function(){advanceTicket(button)})});document.querySelectorAll("[data-menu-add]").forEach(function(button){button.addEventListener("click",function(){demoOrderCount+=1;showToast("أضيف الصنف إلى طلب العرض · العناصر: "+demoOrderCount,"Item added to demo order · items: "+demoOrderCount)})});
  mobileMenu.addEventListener("click",function(){sidebar.classList.add("open");overlay.classList.add("open")});overlay.addEventListener("click",closeSidebar);languageButton.addEventListener("click",function(){setLanguage(isEnglish()?"ar":"en")});themeButton.addEventListener("click",function(){setTheme(root.dataset.theme==="dark"?"light":"dark")});
  commandOpen.addEventListener("click",function(){renderCommands("");dialog.showModal();commandInput.value="";commandInput.focus()});commandClose.addEventListener("click",function(){dialog.close()});commandInput.addEventListener("input",function(){renderCommands(commandInput.value)});dialog.addEventListener("click",function(event){if(event.target===dialog)dialog.close()});document.addEventListener("keydown",function(event){if((event.key==="/"||((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="k"))&&!dialog.open){event.preventDefault();commandOpen.click()}});
  var savedLanguage="ar",savedTheme="light";try{savedLanguage=localStorage.getItem("cp-language")||"ar";savedTheme=localStorage.getItem("cp-demo-theme")||"light"}catch(_error){}setTheme(savedTheme==="dark"?"dark":"light");setLanguage(savedLanguage==="en"?"en":"ar");showView("dashboard");updateKdsCounts();
})();
